# ==========================================
# APPLICATION
# ==========================================

spring.application.name=pustakalaya-backend


# ==========================================
# MYSQL DATABASE
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/pustakalaya?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=snig@123


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ==========================================
# SERVER
# ==========================================

server.port=8083